CRITICAL - 2020-05-27 13:38:55 --> Undefined variable: newnew
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(106): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 106, Array)
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->register()
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 13:39:25 --> Table 'transportation.$newfname' doesn't exist
#0 C:\xampp\htdocs\dev\system\Database\MySQLi\Connection.php(331): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\dev\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\dev\system\Database\BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\dev\system\Database\BaseBuilder.php(1845): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\dev\system\Validation\Rules.php(234): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\dev\system\Validation\Validation.php(294): CodeIgniter\Validation\Rules->is_unique('test3', '$newfname', Array, NULL)
#6 C:\xampp\htdocs\dev\system\Validation\Validation.php(189): CodeIgniter\Validation\Validation->processRules('firstname', 'firstname', 'test3', Array, Array)
#7 C:\xampp\htdocs\dev\system\Controller.php(219): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\dev\app\Controllers\Users.php(176): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->register()
#10 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2020-05-27 13:52:43 --> syntax error, unexpected 'usernameUsers' (T_STRING), expecting ')'
#0 C:\xampp\htdocs\dev\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\dev\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(865): class_exists('\\App\\Controller...', true)
#5 C:\xampp\htdocs\dev\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-05-27 14:40:03 --> Undefined variable: model
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(92): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 92, Array)
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->register()
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 14:40:19 --> Undefined variable: newData
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(103): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 103, Array)
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->register()
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 14:44:26 --> Call to undefined method App\Models\UserModel::all
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(97): CodeIgniter\Model->__call('all', Array)
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->register()
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 15:34:28 --> Undefined variable: incrementuser
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(111): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 111, Array)
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->register()
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 16:03:10 --> syntax error, unexpected '=>' (T_DOUBLE_ARROW)
#0 C:\xampp\htdocs\dev\system\Router\Router.php(192): CodeIgniter\Router\Router->autoRoute('/')
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(789): CodeIgniter\Router\Router->handle('/')
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(360): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 16:03:19 --> Undefined variable: model
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(78): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 78, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(42): App\Controllers\Users->setUserSession(Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:03:33 --> Undefined variable: model
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(78): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 78, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(42): App\Controllers\Users->setUserSession(Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:03:45 --> Undefined variable: model
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(78): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 78, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(42): App\Controllers\Users->setUserSession(Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:04:14 --> Undefined variable: model
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(80): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 80, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(43): App\Controllers\Users->setUserSession(Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:06:31 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dev\system\Model.php(728): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 728, Array)
#1 C:\xampp\htdocs\dev\system\Model.php(557): CodeIgniter\Model->insert(Array, false)
#2 C:\xampp\htdocs\dev\app\Controllers\Users.php(46): CodeIgniter\Model->save(Object(App\Models\UserModel))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-05-27 16:08:33 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dev\system\Model.php(728): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 728, Array)
#1 C:\xampp\htdocs\dev\system\Model.php(557): CodeIgniter\Model->insert(Array, false)
#2 C:\xampp\htdocs\dev\app\Controllers\Users.php(54): CodeIgniter\Model->save(Array)
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-05-27 16:11:01 --> Undefined variable: user
#0 C:\xampp\htdocs\dev\app\Controllers\Users.php(33): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 33, Array)
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-05-27 16:11:35 --> Call to a member function set() on array
#0 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#1 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-05-27 16:23:22 --> print_r() expects parameter 2 to be bool, array given
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r() expec...', 'C:\\xampp\\htdocs...', 44, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(44): print_r('idUsers', Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:24:56 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dev\system\Model.php(863): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 863, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(48): CodeIgniter\Model->update(Array, Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:25:17 --> There is no data to {0}.
#0 C:\xampp\htdocs\dev\system\Model.php(809): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(48): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:25:24 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dev\system\Model.php(863): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 863, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(48): CodeIgniter\Model->update(Array, Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-05-27 16:25:33 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\dev\system\Model.php(863): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 863, Array)
#1 C:\xampp\htdocs\dev\app\Controllers\Users.php(48): CodeIgniter\Model->update(Array, Array)
#2 C:\xampp\htdocs\dev\system\CodeIgniter.php(914): App\Controllers\Users->index()
#3 C:\xampp\htdocs\dev\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\dev\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\dev\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
